name: Publish NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet version'
        required: true

# github.event.inputs.version
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: 🏭 Install psake
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module psake
      - name: 🏭 Configure and run tests
        shell: pwsh
        run: Invoke-Psake ../psakeTasks.ps1 Publish -parameters @{"version"="${{ github.event.inputs.version }}";"actor"="${{ github.actor }}"}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}